# Generated by Django 4.1.13 on 2023-12-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldierData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='killsPerMin',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='scorePerMin',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='winsPercentage',
            field=models.FloatField(),
        ),
    ]
