# Generated by Django 4.1.13 on 2023-12-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldierData', '0002_alter_soldier_killspermin_alter_soldier_scorepermin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPoints', models.IntegerField()),
                ('totalWeapons', models.IntegerField()),
                ('totalKits', models.IntegerField()),
                ('totalVehicals', models.IntegerField()),
                ('totalMedals', models.IntegerField()),
                ('totalAssignments', models.IntegerField()),
                ('totalDogTags', models.IntegerField()),
            ],
        ),
    ]
